VOX/VOX_WEB/Controllers/OrganizerController.cs
using Newtonsoft.Json;
using NLog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using VOX_WEB.Models;
using VOX_WEB.Utils;

namespace VOX_WEB.Controllers
{
    [Authorize]

    public class OrganizerController : Controller
    {
        // GET: Organizer
        private static Logger logger = LogManager.GetCurrentClassLogger();

        public ActionResult Index()
        {
            ViewBag.Version = Guid.NewGuid().ToString().Replace("-", "");

            return View();
        }
        public async Task<PartialViewResult> Edit(string id)
        {
            Organizer res = new Organizer();
            APIExtension api = new APIExtension();
            try
            {
                SessionContext context = new SessionContext();
                var userData = context.GetUserData();
                if (!String.IsNullOrEmpty(id))
                {
                    string endPoint = string.Format("organizers/{0}", id);
                    res = await api.Get<Organizer>(endPoint, userData.token);
                }
               
            }
            catch (Exception e)
            {
                logger.Error<Exception>(e);
            }
          
            return PartialView(res);
        }
        public async Task<JsonResult> getOrganizerAll()
        {
            OrganizerList res = new OrganizerList();

            APIExtension api = new APIExtension();

            try
            {
                SessionContext context = new SessionContext();
                var userData = context.GetUserData();

                string endPoint = "organizers?page=0&perPage=5000";
                res = await api.Get<OrganizerList>(endPoint, userData.token);
                if (res != null && res.data != null)
                {
                    res.data = res.data.OrderByDescending(o => o.id).ToList();
                }
            }
            catch (Exception e)
            {
                logger.Error<Exception>(e);
            }

            return Json(res, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> Save(Organizer input)
        {
            RestResponse res = new RestResponse();

            APIExtension api = new APIExtension();

            try
            {
                SessionContext context = new SessionContext();
                var userData = context.GetUserData();
                if(input.id == null)
                {
                    string endpoint = string.Format("organizers");
                    string resAPI = await api.PostToken(endpoint, input, userData.token);
                    res = JsonConvert.DeserializeObject<RestResponse>(resAPI);

                    if (res != null && res.isSuccess == true)
                    {
                        var resOrg = JsonConvert.DeserializeObject<Organizer>(res.Data);
                        res.Message = "Save Successfully id: " + resOrg.id;
                    }
                }
                else
                {
                    string endpointupdate = string.Format("organizers/{0}", input.id);
                    string resAPI = await api.PutToken(endpointupdate, input, userData.token);
                    res = JsonConvert.DeserializeObject<RestResponse>(resAPI);
                    if (res.isSuccess == true)
                    {
                        res.Message = "Update Successfully id: " + input.id;
                    }
                }
              

            }
            catch (Exception e)
            {
                logger.Error<Exception>(e);
            }

            return Json(res, JsonRequestBehavior.DenyGet);
        }

        public async Task<JsonResult> Delete(Organizer input)
        {
            RestResponse res = new RestResponse();
            APIExtension api = new APIExtension();
            try
            {
                SessionContext context = new SessionContext();
                var userData = context.GetUserData();

                string endPoint = string.Format("organizers/{0}", input.id);
                string resAPI = await api.DeleteToken(endPoint, userData.token);
                res = JsonConvert.DeserializeObject<RestResponse>(resAPI);
            }
            catch (Exception e)
            {
                logger.Error<Exception>(e);
            }

            return Json(res, JsonRequestBehavior.DenyGet);
        }

    }
}

VOX/VOX_WEB/Controllers/SportEventController.cs
using Newtonsoft.Json;
using NLog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using VOX_WEB.Models;
using VOX_WEB.Utils;

namespace VOX_WEB.Controllers
{
    [Authorize]

    public class SportEventController : Controller
    {
        private static Logger logger = LogManager.GetCurrentClassLogger();

        // GET: SportEvent
        public ActionResult Index()
        {
            return View();
        }
        public async Task<PartialViewResult> Edit(string id)
        {
            SportEvent res = new SportEvent();
            APIExtension api = new APIExtension();
            try
            {
                SessionContext context = new SessionContext();
                var userData = context.GetUserData();
                if (!String.IsNullOrEmpty(id))
                {
                    string endPoint = string.Format("sport-events/{0}", id);
                    res = await api.Get<SportEvent>(endPoint, userData.token);
                }
                else
                {
                    res.organizer = new Organizer();
                }

            }
            catch (Exception e)
            {
                logger.Error<Exception>(e);
            }

            return PartialView(res);
        }
        public async Task<JsonResult> getSportEventAll()
        {
            SportEventList res = new SportEventList();
            List<SportEventRes> resSports = new List<SportEventRes>();

            APIExtension api = new APIExtension();

            try
            {
                SessionContext context = new SessionContext();
                var userData = context.GetUserData();

                string endPoint = "sport-events?page=0&perPage=5000";
                res = await api.Get<SportEventList>(endPoint, userData.token);
                if (res != null && res.data != null)
                {
                    res.data = res.data.OrderByDescending(o => o.id).ToList();
                    foreach (var resSport in res.data)
                    {
                        SportEventRes model = new SportEventRes();
                        model.eventDate = resSport.eventDate;
                        model.eventName = resSport.eventName;
                        model.eventType = resSport.eventType;
                        model.id = resSport.id ?? 0;
                        model.organizer = resSport.organizer.organizerName;

                        resSports.Add(model);
                    }
                }
            }
            catch (Exception e)
            {
                logger.Error<Exception>(e);
            }

            return Json(resSports, JsonRequestBehavior.AllowGet);
        }
        public async Task<JsonResult> Save(SportEvent input)
        {
            RestResponse res = new RestResponse();

            APIExtension api = new APIExtension();

            try
            {
                SessionContext context = new SessionContext();
                var userData = context.GetUserData();
                if (input.id == null)
                {
                    string endpoint = string.Format("sport-events");
                    string resAPI = await api.PostToken(endpoint, input, userData.token);
                    res = JsonConvert.DeserializeObject<RestResponse>(resAPI);

                    if (res != null && res.isSuccess == true)
                    {
                        var resOrg = JsonConvert.DeserializeObject<Organizer>(res.Data);
                        res.Message = "Save Successfully id: " + resOrg.id;
                    }
                }
                else
                {
                    string endpointupdate = string.Format("sport-events/{0}", input.id);
                    string resAPI = await api.PutToken(endpointupdate, input, userData.token);
                    res = JsonConvert.DeserializeObject<RestResponse>(resAPI);
                    if (res.isSuccess == true)
                    {
                        res.Message = "Update Successfully id: " + input.id;
                    }
                }
            }
            catch (Exception e)
            {
                logger.Error<Exception>(e);
            }

            return Json(res, JsonRequestBehavior.DenyGet);
        }

        public async Task<JsonResult> Delete(SportEvent input)
        {
            RestResponse res = new RestResponse();
            APIExtension api = new APIExtension();
            try
            {
                SessionContext context = new SessionContext();
                var userData = context.GetUserData();

                string endPoint = string.Format("sport-events/{0}", input.id);
                string resAPI = await api.DeleteToken(endPoint, userData.token);
                res = JsonConvert.DeserializeObject<RestResponse>(resAPI);
            }
            catch (Exception e)
            {
                logger.Error<Exception>(e);
            }

            return Json(res, JsonRequestBehavior.DenyGet);
        }

    }
}

VOX/VOX_WEB/Controllers/UsersController.cs
using Newtonsoft.Json;
using NLog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using VOX_WEB.Models;
using VOX_WEB.Utils;

namespace VOX_WEB.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {
        // GET: Users
        private static Logger logger = LogManager.GetCurrentClassLogger();

        //public ActionResult Index()
        //{
        //    return View();
        //}
        public ActionResult GetUser()
        {
            ViewBag.Version = Guid.NewGuid().ToString().Replace("-", "");
            return View();
        }

        public ActionResult UpdateUser()
        {
            ViewBag.Version = Guid.NewGuid().ToString().Replace("-", "");
            return View();
        }
        public ActionResult DeleteUser()
        {
            ViewBag.Version = Guid.NewGuid().ToString().Replace("-", "");
            return View();
        }
        public ActionResult CreateUser()
        {
            ViewBag.Version = Guid.NewGuid().ToString().Replace("-", "");
            return View();
        }
        public async Task<JsonResult> getUserByID(UserOutput input)
        {
            UserResult res = new UserResult();

            APIExtension api = new APIExtension();

            try
            {
                SessionContext context = new SessionContext();
                var userData = context.GetUserData();

                string endPoint = string.Format("users/{0}", input.id);
                res= await api.Get<UserResult>(endPoint, userData.token);
            }
            catch (Exception e)
            {
                logger.Error<Exception>(e);
            }

            return Json(res, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> UpdateUserAPI(UserResult input)
        {
            UserResult res = new UserResult();

            APIExtension api = new APIExtension();

            try
            {
                SessionContext context = new SessionContext();
                var userData = context.GetUserData();

                string endpointupdate = string.Format("users/{0}", input.id);
                string resAPI = await api.PutToken(endpointupdate, input, userData.token);

                string endPoint = string.Format("users/{0}", input.id);
                res = await api.Get<UserResult>(endPoint, userData.token);
            }
            catch (Exception e)
            {
                logger.Error<Exception>(e);
            }

            return Json(res, JsonRequestBehavior.DenyGet);
        }

        public async Task<JsonResult> CreateUserAPI(UserCreateInput input)
        {
            RestResponse res = new RestResponse();

            APIExtension api = new APIExtension();

            try
            {
                SessionContext context = new SessionContext();
                var userData = context.GetUserData();

                string endpoint = string.Format("users");
                string resAPI = await api.PostToken(endpoint, input, userData.token);
                res = JsonConvert.DeserializeObject<RestResponse>(resAPI);

                if (res != null && res.isSuccess==true)
                {
                    var resLogin = JsonConvert.DeserializeObject<Users>(res.Data);
                    res.Message = "Save Successfully id: " + resLogin.id;
                }

            }
            catch (Exception e)
            {
                logger.Error<Exception>(e);
            }

            return Json(res, JsonRequestBehavior.DenyGet);
        }

        public async Task<JsonResult> DeleteUserAPI(UserResult input)
        {
            RestResponse res = new RestResponse();

            APIExtension api = new APIExtension();

            try
            {
                SessionContext context = new SessionContext();
                var userData = context.GetUserData();

                string endPoint = string.Format("users/{0}", input.id);
                string resAPI = await api.DeleteToken(endPoint, userData.token);
                res = JsonConvert.DeserializeObject<RestResponse>(resAPI);



            }
            catch (Exception e)
            {
                logger.Error<Exception>(e);
            }

            return Json(res, JsonRequestBehavior.DenyGet);
        }
    }
}

VOX/VOX_WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - VOX Test</title>
    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")*@

    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    @*<script src="~/Scripts/modernizr-2.8.3.js"></script>*@


    <link href="~/Assets/plugins/global/plugins.bundle.css" rel="stylesheet" />
    <link href="~/Assets/plugins/custom/prismjs/prismjs.bundle.css" rel="stylesheet" />
    <link href="~/Assets/css/style.bundle.css" rel="stylesheet" />
    <link href="~/Content/Customcss.css?v=20240527" rel="stylesheet" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" />
    <link href="~/Assets/spinner/css/spinner.css" rel="stylesheet" />
    <script src="~/Assets/spinner/js/spinner.js"></script>
    <link href="~/Assets/kendo/css/kendo.common-bootstrap.core.min.css" rel="stylesheet" />
    <link href="~/Assets/kendo/css/kendo.common-bootstrap.min.css" rel="stylesheet" />
    <link href="~/Assets/kendo/css/kendo.default.min.css" rel="stylesheet" />
    <link href="~/Assets/kendo/css/kendo.mobile.all.min.css" rel="stylesheet" />

    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>



    <script src="~/Assets/plugins/global/plugins.bundle.js"></script>

    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
</head>
<body id="kt_body" class="quick-panel-right demo-panel-right offcanvas-right header-fixed subheader-enabled page-loading" style="zoom:80%!important;">

    <div id="kt_header_mobile" class="header-mobile" style="background:#f19191;">
        <!--begin::Logo-->
        <a href="@Url.Action("Index", "Home")">
            <img alt="Logo" src="https://www.voxteneo.com/media/v2wga2ta/vox-logo.svg?width=1" class="logo-default max-h-30px" />
        </a>
        <!--end::Logo-->
        <!--begin::Toolbar-->
        <div class="d-flex align-items-center">
            <button class="btn p-0 burger-icon burger-icon-left ml-4" id="kt_header_mobile_toggle">
                <span></span>
            </button>

        </div>
        <!--end::Toolbar-->
    </div>

    <div class="d-flex flex-column flex-root">
        <!--begin::Page-->
        <div class="d-flex flex-row flex-column-fluid page">
            <!--begin::Wrapper-->
            <div class="d-flex flex-column flex-row-fluid wrapper" id="kt_wrapper">
                <!--begin::Header-->
                <div id="kt_header" class="header header-fixed">
                    <!--begin::Container-->
                    <div class="container d-flex align-items-stretch  ">
                        <!--begin::Left-->
                        <div class="d-flex align-items-stretch mr-3">
                            <!--begin::Header Logo-->
                            <div class="header-logo">
                                <a href="@Url.Action("Index", "Home")">
                                    <img alt="Logo" src="https://www.voxteneo.com/media/v2wga2ta/vox-logo.svg?width=1" class="logo-default max-h-40px" />
                                    @*<img alt="Logo" src="assets/media/logos/logo-letter-1.png" class="logo-sticky max-h-40px" />*@
                                </a>
                            </div>
                            <!--end::Header Logo-->
                            <!--begin::Header Menu Wrapper-->
                            <div class="header-menu-wrapper header-menu-wrapper-left" id="kt_header_menu_wrapper">
                                <!--begin::Header Menu-->
                                <div id="kt_header_menu" class="header-menu header-menu-left header-menu-mobile header-menu-layout-default">
                                    <!--begin::Header Nav-->
                                    <ul class="menu-nav">

                                        <li class="menu-item menu-item-open menu-item-here menu-item-submenu menu-item-rel menu-item-open menu-item-here" data-menu-toggle="click" aria-haspopup="true">
                                            <a href="javascript:;" class="menu-link menu-toggle">
                                                <span class="menu-text">User</span>
                                                <i class="menu-arrow"></i>
                                            </a>
                                            <div class="menu-submenu menu-submenu-classic menu-submenu-left">
                                                <ul class="menu-subnav">
                                                    <li class="menu-item " aria-haspopup="true">
                                                        <a href="@Url.Action("CreateUser", "Users")" class="menu-link">
                                                            <span class="menu-text">Create User</span>
                                                            <span class="menu-desc"></span>
                                                        </a>
                                                    </li>
                                                    <li class="menu-item" aria-haspopup="true">
                                                        <a href="@Url.Action("GetUser", "Users")" class="menu-link">
                                                            <span class="menu-text">Get User</span>
                                                            <span class="menu-desc"></span>
                                                        </a>
                                                    </li>
                                                    <li class="menu-item" aria-haspopup="true">
                                                        <a href="@Url.Action("UpdateUser", "Users")" class="menu-link">
                                                            <span class="menu-text">Update User</span>
                                                            <span class="menu-desc"></span>
                                                        </a>
                                                    </li>
                                                    <li class="menu-item" aria-haspopup="true">
                                                        <a href="@Url.Action("DeleteUser", "Users")" class="menu-link">
                                                            <span class="menu-text">Delete User</span>
                                                            <span class="menu-desc"></span>
                                                        </a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </li>

                                      
                                        <li class="menu-item  menu-item-submenu menu-item-rel menu-item-active">
                                            <a href="@Url.Action("Index", "Organizer")" class="menu-link"><span class="menu-text" >Organizer</span></a>
                                        </li>

                                        <li class="menu-item  menu-item-submenu menu-item-rel menu-item-active" style="width:120px;">
                                            <a href="@Url.Action("Index", "SportEvent")" class="menu-link"><span class="menu-text" >Sport Event</span></a>
                                        </li>
                                    </ul>
                                    <!--end::Header Nav-->

                                </div>
                                <!--end::Header Menu-->
                            </div>


                            <!--end::Header Menu Wrapper-->
                        </div>
                        <!--end::Left-->
                        <!--begin::Topbar-->
                        <div class="nav navbar-nav navbar-right" style="margin-top:20px;">

                            <!--begin::User-->
                            <div class="dropdown">
                                <!--begin::Toggle-->
                                <div class="topbar-item" style="float:right;">
                                    <div class="btn btn-icon btn-hover-transparent-white d-flex align-items-center btn-lg px-md-2 w-md-auto" id="kt_quick_user_toggle">
                                        <span style="color:black;" class=" opacity-70 font-weight-bold font-size-base d-none d-md-inline mr-1">Hi,</span>
                                        <span style="color:black;" class=" opacity-90 font-weight-bolder font-size-base d-none d-md-inline mr-4">@User.Identity.Name</span>

                                        <a class="btn btn-info btn-sm" href="@Url.Action("Logout","Account")" style="background:#6969d1;"><i class="glyphicon glyphicon-log-out" aria-hidden="true"> </i></a>

                                    </div>
                                </div>
                                <!--end::Toggle-->
                            </div>
                            <!--end::User-->
                        </div>
                        <!--end::Topbar-->
                    </div>
                    <!--end::Container-->
                </div>
                <!--end::Header-->
                <!--begin::Content-->
                <div class="content d-flex flex-column flex-column-fluid" id="kt_content">
                    <!--begin::Entry-->
                    <div class="d-flex flex-column-fluid">
                        <!--begin::Container-->
                        <div class="container content-container">
                            <div class="row">
                                @RenderBody()
                                <br />
                            </div>
                        </div>
                        <!--end::Container-->
                    </div>
                    <!--end::Entry-->
                </div>
                <!--end::Content-->

            </div>
            <!--end::Wrapper-->
        </div>
        <!--end::Page-->
    </div>
    <!--end::Main-->
    @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", New With {.area = ""}, New With {.class = "navbar-brand"})
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                </div>
            </div>
        </div>*@
    @*<div class="container body-content">
            @RenderBody()
            <br />
        </div>*@
    <!--begin::Global Config(global config for global JS scripts)-->
    <script>var KTAppSettings = { "breakpoints": { "sm": 576, "md": 768, "lg": 992, "xl": 1200, "xxl": 1200 }, "colors": { "theme": { "base": { "white": "#ffffff", "primary": "#6993FF", "secondary": "#E5EAEE", "success": "#1BC5BD", "info": "#8950FC", "warning": "#FFA800", "danger": "#F64E60", "light": "#F3F6F9", "dark": "#212121" }, "light": { "white": "#ffffff", "primary": "#E1E9FF", "secondary": "#ECF0F3", "success": "#C9F7F5", "info": "#EEE5FF", "warning": "#FFF4DE", "danger": "#FFE2E5", "light": "#F3F6F9", "dark": "#D6D6E0" }, "inverse": { "white": "#ffffff", "primary": "#ffffff", "secondary": "#212121", "success": "#ffffff", "info": "#ffffff", "warning": "#ffffff", "danger": "#ffffff", "light": "#464E5F", "dark": "#ffffff" } }, "gray": { "gray-100": "#F3F6F9", "gray-200": "#ECF0F3", "gray-300": "#E5EAEE", "gray-400": "#D6D6E0", "gray-500": "#B5B5C3", "gray-600": "#80808F", "gray-700": "#464E5F", "gray-800": "#1B283F", "gray-900": "#212121" } }, "font-family": "Poppins" };</script>
    <!--end::Global Config-->



    <script src="~/Assets/plugins/custom/prismjs/prismjs.bundle.js"></script>
    <script src="~/Assets/js/scripts.bundle.js"></script>
    <script src="~/Assets/plugins/custom/fullcalendar/fullcalendar.bundle.js"></script>
    <script src="~/Assets/js/pages/widgets.js"></script>
    <script src="~/Assets/kendo/js/kendo.all.min.js"></script>
    <script src="~/Assets/sweetalert/sweetalert2.all.js"></script>
    <script src="~/Assets/sweetalert/sweetalert2.min.js"></script>

</body>
</html>